export const staticQuizList = [
    {
        "id": 2202,
        "description": "abc",
        "quizTime": 6,
        "userId": 2,
        "startTime": "2017-01-24T00:03:31.593",
        "endTime": null,
        "expiredTime": "2017-01-24T00:03:45.593",
        "status": "not start",
        "numberQuestions": 5,
        "score": null,
        "questions": null,
        "userStartQuiz": 0
    },
    {
        "id": 2252,
        "description": "abc",
        "quizTime": 6,
        "userId": 2,
        "startTime": "2017-01-24T00:03:31.593",
        "endTime": null,
        "expiredTime": "2017-01-24T00:03:45.593",
        "status": "not start",
        "numberQuestions": 6,
        "score": null,
        "questions": null,
        "userStartQuiz": 1650512868171
    },
    {
        "id": 2553,
        "description": "abc",
        "quizTime": 5,
        "userId": 2,
        "startTime": "2017-01-24T00:03:31.593",
        "endTime": null,
        "expiredTime": "2017-01-24T00:03:45.593",
        "status": "not start",
        "numberQuestions": 4,
        "score": null,
        "questions": null,
        "userStartQuiz": 1650513535392
    },
    {
        "id": 2102,
        "description": "abc",
        "quizTime": 15,
        "userId": 2,
        "startTime": null,
        "endTime": null,
        "expiredTime": null,
        "status": "not start",
        "numberQuestions": 15,
        "score": null,
        "questions": null,
        "userStartQuiz": 0
    },
    {
        "id": 2002,
        "description": "abc",
        "quizTime": 15,
        "userId": 2,
        "startTime": null,
        "endTime": null,
        "expiredTime": null,
        "status": "not start",
        "numberQuestions": 15,
        "score": null,
        "questions": null,
        "userStartQuiz": 1650513733764
    },
    {
        "id": 2152,
        "description": "abc",
        "quizTime": 15,
        "userId": 2,
        "startTime": null,
        "endTime": null,
        "expiredTime": null,
        "status": "not start",
        "numberQuestions": 14,
        "score": null,
        "questions": null,
        "userStartQuiz": 1650514031713
    },
    {
        "id": 2052,
        "description": "abc",
        "quizTime": 15,
        "userId": 2,
        "startTime": null,
        "endTime": null,
        "expiredTime": null,
        "status": "not start",
        "numberQuestions": 15,
        "score": null,
        "questions": null,
        "userStartQuiz": 1650515165971
    },
    {
        "id": 1952,
        "description": "abc",
        "quizTime": 15,
        "userId": 2,
        "startTime": null,
        "endTime": "2022-04-13T10:26:43.594939",
        "expiredTime": null,
        "status": "done",
        "numberQuestions": 15,
        "score": "11/15  (73.33%)",
        "questions": null,
        "userStartQuiz": 1650515180398
    },
    {
        "id": 2302,
        "description": "abc",
        "quizTime": 6,
        "userId": 2,
        "startTime": "2017-01-24T00:03:31.593",
        "endTime": null,
        "expiredTime": "2017-01-24T00:03:45.593",
        "status": "not start",
        "numberQuestions": 6,
        "score": null,
        "questions": null,
        "userStartQuiz": 0
    },
    {
        "id": 2552,
        "description": "abc",
        "quizTime": 15,
        "userId": 2,
        "startTime": "2017-01-24T00:03:31.593",
        "endTime": null,
        "expiredTime": "2017-01-24T00:03:45.593",
        "status": "not start",
        "numberQuestions": 14,
        "score": null,
        "questions": null,
        "userStartQuiz": 0
    },
    {
        "id": 2603,
        "description": "abc",
        "quizTime": 3,
        "userId": 2,
        "startTime": "2017-01-24T00:03:31.593",
        "endTime": null,
        "expiredTime": "2017-01-24T00:03:45.593",
        "status": "not start",
        "numberQuestions": 3,
        "score": null,
        "questions": null,
        "userStartQuiz": 0
    },
    {
        "id": 2606,
        "description": "abc",
        "quizTime": 3,
        "userId": 2,
        "startTime": "2017-01-24T00:03:31.593",
        "endTime": null,
        "expiredTime": "2017-01-24T00:03:45.593",
        "status": "not start",
        "numberQuestions": 3,
        "score": null,
        "questions": null,
        "userStartQuiz": 0
    },
    {
        "id": 2652,
        "description": "abc",
        "quizTime": 3,
        "userId": 2,
        "startTime": "2017-01-24T00:03:31.593",
        "endTime": "2022-04-13T10:53:33.085779",
        "expiredTime": "2017-01-24T00:03:45.593",
        "status": "done",
        "numberQuestions": 3,
        "score": "0/3  (0.0%)",
        "questions": null,
        "userStartQuiz": 0
    },
    {
        "id": 1702,
        "description": "abc",
        "quizTime": 15,
        "userId": 2,
        "startTime": null,
        "endTime": null,
        "expiredTime": null,
        "status": "done",
        "numberQuestions": 15,
        "score": "0/15  (0.0%)",
        "questions": null,
        "userStartQuiz": 0
    },
    {
        "id": 1752,
        "description": "abc",
        "quizTime": 15,
        "userId": 2,
        "startTime": null,
        "endTime": null,
        "expiredTime": null,
        "status": "done",
        "numberQuestions": 15,
        "score": "0/15  (0.0%)",
        "questions": null,
        "userStartQuiz": 0
    },
    {
        "id": 1753,
        "description": "abc",
        "quizTime": 15,
        "userId": 2,
        "startTime": null,
        "endTime": null,
        "expiredTime": null,
        "status": "done",
        "numberQuestions": 15,
        "score": "0/15  (0.0%)",
        "questions": null,
        "userStartQuiz": 0
    },
    {
        "id": 1802,
        "description": "abc",
        "quizTime": 15,
        "userId": 2,
        "startTime": null,
        "endTime": null,
        "expiredTime": null,
        "status": "done",
        "numberQuestions": 15,
        "score": "0/15  (0.0%)",
        "questions": null,
        "userStartQuiz": 0
    },
    {
        "id": 1852,
        "description": "abc",
        "quizTime": 15,
        "userId": 2,
        "startTime": null,
        "endTime": null,
        "expiredTime": null,
        "status": "done",
        "numberQuestions": 15,
        "score": "0/15  (0.0%)",
        "questions": null,
        "userStartQuiz": 0
    },
    {
        "id": 1902,
        "description": "abc",
        "quizTime": 15,
        "userId": 2,
        "startTime": null,
        "endTime": null,
        "expiredTime": null,
        "status": "done",
        "numberQuestions": 15,
        "score": "0/15  (0.0%)",
        "questions": null,
        "userStartQuiz": 0
    },
    {
        "id": 2655,
        "description": "abc",
        "quizTime": 3,
        "userId": 2,
        "startTime": "2017-01-24T00:03:31.593",
        "endTime": "2022-04-20T10:22:59.309115",
        "expiredTime": "2017-01-24T00:03:45.593",
        "status": "done",
        "numberQuestions": 3,
        "score": "1/3  (33.33%)",
        "questions": null,
        "userStartQuiz": 0
    },
    {
        "id": 2658,
        "description": "abc",
        "quizTime": 3,
        "userId": 2,
        "startTime": "2017-01-24T00:03:31.593",
        "endTime": null,
        "expiredTime": "2017-01-24T00:03:45.593",
        "status": "not start",
        "numberQuestions": 3,
        "score": null,
        "questions": null,
        "userStartQuiz": 0
    },
    {
        "id": 2802,
        "description": "abc",
        "quizTime": 5,
        "userId": 2,
        "startTime": "2017-01-24T00:03:31.593",
        "endTime": null,
        "expiredTime": "2017-01-24T00:03:45.593",
        "status": "not start",
        "numberQuestions": 5,
        "score": null,
        "questions": null,
        "userStartQuiz": 0
    },
    {
        "id": 2852,
        "description": "abc",
        "quizTime": 5,
        "userId": 2,
        "startTime": "2017-01-24T00:03:31.593",
        "endTime": "2022-04-13T13:55:02.628057",
        "expiredTime": "2017-01-24T00:03:45.593",
        "status": "done",
        "numberQuestions": 5,
        "score": "0/5  (0.0%)",
        "questions": null,
        "userStartQuiz": 0
    },
    {
        "id": 2902,
        "description": "abc",
        "quizTime": 5,
        "userId": 2,
        "startTime": "2022-04-01T13:41:00",
        "endTime": null,
        "expiredTime": "2022-04-02T13:41:00",
        "status": "not start",
        "numberQuestions": 5,
        "score": null,
        "questions": null,
        "userStartQuiz": 0
    }
]